FIX_TIME: 1000
INITIAL_STOP_DELAY: 150
MAX_REACTION_TIME: 1000
MAX_STOP_DELAY: 400
MIN_STOP_DELAY: 100
N_EXP_A_BLOCKS: 6
N_EXP_A_TRIALS: 120
N_TRN_A_TRIALS: 15
N_TRN_B_TRIALS: 27
REACTION_KEYS:
- a
- l
STOP_DELAY_STEP: 50
